{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyN4EIRq0+i3swjcHrE8ypxF",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/RGI985/Diease_Classification/blob/main/model.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "M4lEmGnRn7Jj"
      },
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2b31c67a",
        "outputId": "32355004-7c58-440b-e889-0b6dfe111c12"
      },
      "source": [
        "!pip install mlflow"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting mlflow\n",
            "  Downloading mlflow-3.15.1-py3-none-any.whl.metadata (49 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m49.7/49.7 kB\u001b[0m \u001b[31m2.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting mlflow-skinny==3.15.1 (from mlflow)\n",
            "  Downloading mlflow_skinny-3.15.1-py3-none-any.whl.metadata (50 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m50.5/50.5 kB\u001b[0m \u001b[31m3.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hCollecting mlflow-tracing==3.15.1 (from mlflow)\n",
            "  Downloading mlflow_tracing-3.15.1-py3-none-any.whl.metadata (19 kB)\n",
            "Collecting Flask-CORS<7 (from mlflow)\n",
            "  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)\n",
            "Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)\n",
            "Requirement already satisfied: aiohttp<4,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.3)\n",
            "Collecting alembic!=1.10.0,<2 (from mlflow)\n",
            "  Downloading alembic-1.19.1-py3-none-any.whl.metadata (7.3 kB)\n",
            "Collecting cryptography<50,>=43.0.0 (from mlflow)\n",
            "  Downloading cryptography-49.0.0-cp311-abi3-manylinux_2_34_x86_64.whl.metadata (4.3 kB)\n",
            "Collecting docker<8,>=4.0.0 (from mlflow)\n",
            "  Downloading docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)\n",
            "Collecting graphene<4 (from mlflow)\n",
            "  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)\n",
            "Collecting gunicorn<27 (from mlflow)\n",
            "  Downloading gunicorn-26.1.0-py3-none-any.whl.metadata (5.5 kB)\n",
            "Collecting huey<4,>=2.5.4 (from mlflow)\n",
            "  Downloading huey-3.3.4-py3-none-any.whl.metadata (5.6 kB)\n",
            "Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)\n",
            "Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)\n",
            "Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.3)\n",
            "Requirement already satisfied: pyarrow<26,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)\n",
            "Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)\n",
            "Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)\n",
            "Collecting skops<1 (from mlflow)\n",
            "  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)\n",
            "Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.52)\n",
            "Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (6.2.6)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (8.4.2)\n",
            "Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (3.1.2)\n",
            "Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.15.1->mlflow)\n",
            "  Downloading databricks_sdk-0.133.0-py3-none-any.whl.metadata (44 kB)\n",
            "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m44.0/44.0 kB\u001b[0m \u001b[31m2.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hRequirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.141.1)\n",
            "Collecting gitpython<4,>=3.1.9 (from mlflow-skinny==3.15.1->mlflow)\n",
            "  Downloading gitpython-3.1.59-py3-none-any.whl.metadata (13 kB)\n",
            "Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (9.0.0)\n",
            "Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.43.0)\n",
            "Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.15.1->mlflow)\n",
            "  Downloading opentelemetry_proto-1.44.0-py3-none-any.whl.metadata (2.3 kB)\n",
            "Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.43.0)\n",
            "Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (26.3)\n",
            "Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (5.29.6)\n",
            "Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (2.13.4)\n",
            "Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.2.2)\n",
            "Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (6.0.3)\n",
            "Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (2.32.4)\n",
            "Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.6.0)\n",
            "Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (1.6.0)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (4.16.0)\n",
            "Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.15.1->mlflow) (0.52.3)\n",
            "Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (2.7.1)\n",
            "Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)\n",
            "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)\n",
            "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)\n",
            "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)\n",
            "Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.2)\n",
            "Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.24.5)\n",
            "Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.1.3)\n",
            "Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography<50,>=43.0.0->mlflow) (2.1.1)\n",
            "Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)\n",
            "Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)\n",
            "Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)\n",
            "Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)\n",
            "Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)\n",
            "Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)\n",
            "Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)\n",
            "  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)\n",
            "Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)\n",
            "  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)\n",
            "Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (2.9.0.post0)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.63.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (11.3.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.3)\n",
            "Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)\n",
            "Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)\n",
            "Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.18.0)\n",
            "Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.5)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography<50,>=43.0.0->mlflow) (3.0)\n",
            "Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (2.49.0)\n",
            "Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.4.4)\n",
            "Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.15.1->mlflow) (0.0.5)\n",
            "Collecting gitdb<5,>=4.0.1 (from gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow)\n",
            "  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)\n",
            "Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.15.1->mlflow) (4.1.0)\n",
            "Requirement already satisfied: opentelemetry-semantic-conventions==0.64b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.15.1->mlflow) (0.64b0)\n",
            "Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.2)\n",
            "Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (0.8.0)\n",
            "Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.1->mlflow) (2.46.4)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (3.4.9)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (3.18)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.1->mlflow) (2026.7.22)\n",
            "Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette<2->mlflow-skinny==3.15.1->mlflow) (4.14.2)\n",
            "Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.15.1->mlflow) (0.16.0)\n",
            "Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.15.1->mlflow)\n",
            "  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)\n",
            "Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.4.2)\n",
            "Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (4.9.1)\n",
            "Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.1->mlflow) (0.6.4)\n",
            "Downloading mlflow-3.15.1-py3-none-any.whl (11.2 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m11.2/11.2 MB\u001b[0m \u001b[31m81.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading mlflow_skinny-3.15.1-py3-none-any.whl (3.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m3.6/3.6 MB\u001b[0m \u001b[31m79.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading mlflow_tracing-3.15.1-py3-none-any.whl (1.8 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.8/1.8 MB\u001b[0m \u001b[31m46.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading alembic-1.19.1-py3-none-any.whl (265 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m265.9/265.9 kB\u001b[0m \u001b[31m15.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading cryptography-49.0.0-cp311-abi3-manylinux_2_34_x86_64.whl (4.7 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m4.7/4.7 MB\u001b[0m \u001b[31m68.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading docker-7.2.0-py3-none-any.whl (148 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m148.8/148.8 kB\u001b[0m \u001b[31m12.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading flask_cors-6.0.5-py3-none-any.whl (16 kB)\n",
            "Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m114.9/114.9 kB\u001b[0m \u001b[31m8.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading gunicorn-26.1.0-py3-none-any.whl (216 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m216.2/216.2 kB\u001b[0m \u001b[31m17.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading huey-3.3.4-py3-none-any.whl (123 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m123.9/123.9 kB\u001b[0m \u001b[31m8.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading skops-0.14.0-py3-none-any.whl (132 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m132.2/132.2 kB\u001b[0m \u001b[31m11.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading databricks_sdk-0.133.0-py3-none-any.whl (1.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.1/1.1 MB\u001b[0m \u001b[31m56.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading gitpython-3.1.59-py3-none-any.whl (220 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m221.0/221.0 kB\u001b[0m \u001b[31m19.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading graphql_core-3.2.11-py3-none-any.whl (214 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m214.9/214.9 kB\u001b[0m \u001b[31m17.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)\n",
            "Downloading opentelemetry_proto-1.44.0-py3-none-any.whl (72 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m72.5/72.5 kB\u001b[0m \u001b[31m3.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading gitdb-4.0.12-py3-none-any.whl (62 kB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m62.8/62.8 kB\u001b[0m \u001b[31m2.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading smmap-5.0.3-py3-none-any.whl (24 kB)\n",
            "Installing collected packages: huey, smmap, opentelemetry-proto, gunicorn, graphql-core, graphql-relay, gitdb, docker, cryptography, alembic, skops, graphene, gitpython, Flask-CORS, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow\n",
            "  Attempting uninstall: cryptography\n",
            "    Found existing installation: cryptography 50.0.0\n",
            "    Uninstalling cryptography-50.0.0:\n",
            "      Successfully uninstalled cryptography-50.0.0\n",
            "Successfully installed Flask-CORS-6.0.5 alembic-1.19.1 cryptography-49.0.0 databricks-sdk-0.133.0 docker-7.2.0 gitdb-4.0.12 gitpython-3.1.59 graphene-3.4.3 graphql-core-3.2.11 graphql-relay-3.2.0 gunicorn-26.1.0 huey-3.3.4 mlflow-3.15.1 mlflow-skinny-3.15.1 mlflow-tracing-3.15.1 opentelemetry-proto-1.44.0 skops-0.14.0 smmap-5.0.3\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import kagglehub\n",
        "path = kagglehub.dataset_download(\"dhivyeshrk/diseases-and-symptoms-dataset\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "CSa8RrVApFWb",
        "outputId": "4d78e301-dba8-4754-c09c-5bc7521be56c"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Downloading to /root/.cache/kagglehub/datasets/dhivyeshrk/diseases-and-symptoms-dataset/1.archive...\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "100%|██████████| 2.81M/2.81M [00:00<00:00, 121MB/s]"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Extracting files...\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "path"
      ],
      "metadata": {
        "id": "VBBoeDhKpMKn"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "\n",
        "# List the contents of the directory\n",
        "files_in_path = os.listdir(path)\n",
        "print(f\"Files in the Kaggle path: {files_in_path}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "_rq8o0RqpR08",
        "outputId": "e26e6213-abf0-4ccb-9f6a-69e61e342781"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Files in the Kaggle path: ['Final_Augmented_dataset_Diseases_and_Symptoms.csv']\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "54469074",
        "outputId": "fad31045-11c7-48f2-bd62-4def85bc3f3d"
      },
      "source": [
        "import pandas as pd\n",
        "\n",
        "# Assuming the CSV file is directly in the 'path' directory and is the only one\n",
        "csv_file_path = os.path.join(path, files_in_path[0])\n",
        "print(csv_file_path)\n",
        "df = pd.read_csv(csv_file_path)\n",
        "\n",
        "print(\"Dataset loaded successfully. Here are the first 5 rows:\")\n",
        "print(df.head())"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/root/.cache/kagglehub/datasets/dhivyeshrk/diseases-and-symptoms-dataset/versions/1/Final_Augmented_dataset_Diseases_and_Symptoms.csv\n",
            "Dataset loaded successfully. Here are the first 5 rows:\n",
            "         diseases  anxiety and nervousness  depression  shortness of breath  \\\n",
            "0  panic disorder                        1           0                    1   \n",
            "1  panic disorder                        0           0                    1   \n",
            "2  panic disorder                        1           1                    1   \n",
            "3  panic disorder                        1           0                    0   \n",
            "4  panic disorder                        1           1                    0   \n",
            "\n",
            "   depressive or psychotic symptoms  sharp chest pain  dizziness  insomnia  \\\n",
            "0                                 1                 0          0         0   \n",
            "1                                 1                 0          1         1   \n",
            "2                                 1                 0          1         1   \n",
            "3                                 1                 0          1         1   \n",
            "4                                 0                 0          0         1   \n",
            "\n",
            "   abnormal involuntary movements  chest tightness  ...  \\\n",
            "0                               0                1  ...   \n",
            "1                               0                0  ...   \n",
            "2                               0                0  ...   \n",
            "3                               1                0  ...   \n",
            "4                               1                1  ...   \n",
            "\n",
            "   stuttering or stammering  problems with orgasm  nose deformity  \\\n",
            "0                         0                     0               0   \n",
            "1                         0                     0               0   \n",
            "2                         0                     0               0   \n",
            "3                         0                     0               0   \n",
            "4                         0                     0               0   \n",
            "\n",
            "   lump over jaw  sore in nose  hip weakness  back swelling  \\\n",
            "0              0             0             0              0   \n",
            "1              0             0             0              0   \n",
            "2              0             0             0              0   \n",
            "3              0             0             0              0   \n",
            "4              0             0             0              0   \n",
            "\n",
            "   ankle stiffness or tightness  ankle weakness  neck weakness  \n",
            "0                             0               0              0  \n",
            "1                             0               0              0  \n",
            "2                             0               0              0  \n",
            "3                             0               0              0  \n",
            "4                             0               0              0  \n",
            "\n",
            "[5 rows x 378 columns]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "df.head()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 394
        },
        "id": "NwmF-V-hqBTO",
        "outputId": "45d38287-6950-4e48-ee6b-2441270d17f4"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "         diseases  anxiety and nervousness  depression  shortness of breath  \\\n",
              "0  panic disorder                        1           0                    1   \n",
              "1  panic disorder                        0           0                    1   \n",
              "2  panic disorder                        1           1                    1   \n",
              "3  panic disorder                        1           0                    0   \n",
              "4  panic disorder                        1           1                    0   \n",
              "\n",
              "   depressive or psychotic symptoms  sharp chest pain  dizziness  insomnia  \\\n",
              "0                                 1                 0          0         0   \n",
              "1                                 1                 0          1         1   \n",
              "2                                 1                 0          1         1   \n",
              "3                                 1                 0          1         1   \n",
              "4                                 0                 0          0         1   \n",
              "\n",
              "   abnormal involuntary movements  chest tightness  ...  \\\n",
              "0                               0                1  ...   \n",
              "1                               0                0  ...   \n",
              "2                               0                0  ...   \n",
              "3                               1                0  ...   \n",
              "4                               1                1  ...   \n",
              "\n",
              "   stuttering or stammering  problems with orgasm  nose deformity  \\\n",
              "0                         0                     0               0   \n",
              "1                         0                     0               0   \n",
              "2                         0                     0               0   \n",
              "3                         0                     0               0   \n",
              "4                         0                     0               0   \n",
              "\n",
              "   lump over jaw  sore in nose  hip weakness  back swelling  \\\n",
              "0              0             0             0              0   \n",
              "1              0             0             0              0   \n",
              "2              0             0             0              0   \n",
              "3              0             0             0              0   \n",
              "4              0             0             0              0   \n",
              "\n",
              "   ankle stiffness or tightness  ankle weakness  neck weakness  \n",
              "0                             0               0              0  \n",
              "1                             0               0              0  \n",
              "2                             0               0              0  \n",
              "3                             0               0              0  \n",
              "4                             0               0              0  \n",
              "\n",
              "[5 rows x 378 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-99051d24-e044-4d73-847a-2014b6c85024\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>diseases</th>\n",
              "      <th>anxiety and nervousness</th>\n",
              "      <th>depression</th>\n",
              "      <th>shortness of breath</th>\n",
              "      <th>depressive or psychotic symptoms</th>\n",
              "      <th>sharp chest pain</th>\n",
              "      <th>dizziness</th>\n",
              "      <th>insomnia</th>\n",
              "      <th>abnormal involuntary movements</th>\n",
              "      <th>chest tightness</th>\n",
              "      <th>...</th>\n",
              "      <th>stuttering or stammering</th>\n",
              "      <th>problems with orgasm</th>\n",
              "      <th>nose deformity</th>\n",
              "      <th>lump over jaw</th>\n",
              "      <th>sore in nose</th>\n",
              "      <th>hip weakness</th>\n",
              "      <th>back swelling</th>\n",
              "      <th>ankle stiffness or tightness</th>\n",
              "      <th>ankle weakness</th>\n",
              "      <th>neck weakness</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>panic disorder</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>...</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>panic disorder</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>...</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>panic disorder</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>...</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>panic disorder</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>...</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>panic disorder</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>...</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>5 rows × 378 columns</p>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-99051d24-e044-4d73-847a-2014b6c85024')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-99051d24-e044-4d73-847a-2014b6c85024 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-99051d24-e044-4d73-847a-2014b6c85024');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df"
            }
          },
          "metadata": {},
          "execution_count": 12
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "df.info()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Z05AGAIxqDoi",
        "outputId": "4d4db71b-6c5f-42fa-fd52-8089819dec59"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 246945 entries, 0 to 246944\n",
            "Columns: 378 entries, diseases to neck weakness\n",
            "dtypes: int64(377), object(1)\n",
            "memory usage: 712.2+ MB\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "v2fpBptTqWI5"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "df.describe()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 401
        },
        "id": "gsQljyojqX6B",
        "outputId": "84311f6c-7629-4c7d-e58a-7ed97890cdb2"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "       anxiety and nervousness     depression  shortness of breath  \\\n",
              "count            246945.000000  246945.000000        246945.000000   \n",
              "mean                  0.039235       0.042746             0.086440   \n",
              "std                   0.194155       0.202285             0.281014   \n",
              "min                   0.000000       0.000000             0.000000   \n",
              "25%                   0.000000       0.000000             0.000000   \n",
              "50%                   0.000000       0.000000             0.000000   \n",
              "75%                   0.000000       0.000000             0.000000   \n",
              "max                   1.000000       1.000000             1.000000   \n",
              "\n",
              "       depressive or psychotic symptoms  sharp chest pain      dizziness  \\\n",
              "count                     246945.000000     246945.000000  246945.000000   \n",
              "mean                           0.061001          0.097252       0.069943   \n",
              "std                            0.239333          0.296302       0.255051   \n",
              "min                            0.000000          0.000000       0.000000   \n",
              "25%                            0.000000          0.000000       0.000000   \n",
              "50%                            0.000000          0.000000       0.000000   \n",
              "75%                            0.000000          0.000000       0.000000   \n",
              "max                            1.000000          1.000000       1.000000   \n",
              "\n",
              "            insomnia  abnormal involuntary movements  chest tightness  \\\n",
              "count  246945.000000                   246945.000000    246945.000000   \n",
              "mean        0.039410                        0.040572         0.037871   \n",
              "std         0.194568                        0.197296         0.190884   \n",
              "min         0.000000                        0.000000         0.000000   \n",
              "25%         0.000000                        0.000000         0.000000   \n",
              "50%         0.000000                        0.000000         0.000000   \n",
              "75%         0.000000                        0.000000         0.000000   \n",
              "max         1.000000                        1.000000         1.000000   \n",
              "\n",
              "        palpitations  ...  stuttering or stammering  problems with orgasm  \\\n",
              "count  246945.000000  ...                  246945.0              246945.0   \n",
              "mean        0.024876  ...                       0.0                   0.0   \n",
              "std         0.155747  ...                       0.0                   0.0   \n",
              "min         0.000000  ...                       0.0                   0.0   \n",
              "25%         0.000000  ...                       0.0                   0.0   \n",
              "50%         0.000000  ...                       0.0                   0.0   \n",
              "75%         0.000000  ...                       0.0                   0.0   \n",
              "max         1.000000  ...                       0.0                   0.0   \n",
              "\n",
              "       nose deformity  lump over jaw   sore in nose  hip weakness  \\\n",
              "count        246945.0       246945.0  246945.000000      246945.0   \n",
              "mean              0.0            0.0       0.001385           0.0   \n",
              "std               0.0            0.0       0.037189           0.0   \n",
              "min               0.0            0.0       0.000000           0.0   \n",
              "25%               0.0            0.0       0.000000           0.0   \n",
              "50%               0.0            0.0       0.000000           0.0   \n",
              "75%               0.0            0.0       0.000000           0.0   \n",
              "max               0.0            0.0       1.000000           0.0   \n",
              "\n",
              "       back swelling  ankle stiffness or tightness  ankle weakness  \\\n",
              "count       246945.0                      246945.0   246945.000000   \n",
              "mean             0.0                           0.0        0.000073   \n",
              "std              0.0                           0.0        0.008537   \n",
              "min              0.0                           0.0        0.000000   \n",
              "25%              0.0                           0.0        0.000000   \n",
              "50%              0.0                           0.0        0.000000   \n",
              "75%              0.0                           0.0        0.000000   \n",
              "max              0.0                           0.0        1.000000   \n",
              "\n",
              "       neck weakness  \n",
              "count       246945.0  \n",
              "mean             0.0  \n",
              "std              0.0  \n",
              "min              0.0  \n",
              "25%              0.0  \n",
              "50%              0.0  \n",
              "75%              0.0  \n",
              "max              0.0  \n",
              "\n",
              "[8 rows x 377 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-b9b1a5b9-eb0d-432e-8a71-465437827f90\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>anxiety and nervousness</th>\n",
              "      <th>depression</th>\n",
              "      <th>shortness of breath</th>\n",
              "      <th>depressive or psychotic symptoms</th>\n",
              "      <th>sharp chest pain</th>\n",
              "      <th>dizziness</th>\n",
              "      <th>insomnia</th>\n",
              "      <th>abnormal involuntary movements</th>\n",
              "      <th>chest tightness</th>\n",
              "      <th>palpitations</th>\n",
              "      <th>...</th>\n",
              "      <th>stuttering or stammering</th>\n",
              "      <th>problems with orgasm</th>\n",
              "      <th>nose deformity</th>\n",
              "      <th>lump over jaw</th>\n",
              "      <th>sore in nose</th>\n",
              "      <th>hip weakness</th>\n",
              "      <th>back swelling</th>\n",
              "      <th>ankle stiffness or tightness</th>\n",
              "      <th>ankle weakness</th>\n",
              "      <th>neck weakness</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>count</th>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>...</td>\n",
              "      <td>246945.0</td>\n",
              "      <td>246945.0</td>\n",
              "      <td>246945.0</td>\n",
              "      <td>246945.0</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.0</td>\n",
              "      <td>246945.0</td>\n",
              "      <td>246945.0</td>\n",
              "      <td>246945.000000</td>\n",
              "      <td>246945.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>mean</th>\n",
              "      <td>0.039235</td>\n",
              "      <td>0.042746</td>\n",
              "      <td>0.086440</td>\n",
              "      <td>0.061001</td>\n",
              "      <td>0.097252</td>\n",
              "      <td>0.069943</td>\n",
              "      <td>0.039410</td>\n",
              "      <td>0.040572</td>\n",
              "      <td>0.037871</td>\n",
              "      <td>0.024876</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.001385</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.000073</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>std</th>\n",
              "      <td>0.194155</td>\n",
              "      <td>0.202285</td>\n",
              "      <td>0.281014</td>\n",
              "      <td>0.239333</td>\n",
              "      <td>0.296302</td>\n",
              "      <td>0.255051</td>\n",
              "      <td>0.194568</td>\n",
              "      <td>0.197296</td>\n",
              "      <td>0.190884</td>\n",
              "      <td>0.155747</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.037189</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.008537</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>min</th>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>25%</th>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>50%</th>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>75%</th>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.000000</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>max</th>\n",
              "      <td>1.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>...</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>0.0</td>\n",
              "      <td>1.000000</td>\n",
              "      <td>0.0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>8 rows × 377 columns</p>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-b9b1a5b9-eb0d-432e-8a71-465437827f90')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-b9b1a5b9-eb0d-432e-8a71-465437827f90 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-b9b1a5b9-eb0d-432e-8a71-465437827f90');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe"
            }
          },
          "metadata": {},
          "execution_count": 14
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "df.shape"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "XLJwFfjvqkuA",
        "outputId": "dd690d51-3c1d-4e45-b0dd-fd469fb89004"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(246945, 378)"
            ]
          },
          "metadata": {},
          "execution_count": 15
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "df.columns"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Y0j-7-nGqzmV",
        "outputId": "45101452-8891-4d17-9d94-5b398a38da66"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Index(['diseases', 'anxiety and nervousness', 'depression',\n",
              "       'shortness of breath', 'depressive or psychotic symptoms',\n",
              "       'sharp chest pain', 'dizziness', 'insomnia',\n",
              "       'abnormal involuntary movements', 'chest tightness',\n",
              "       ...\n",
              "       'stuttering or stammering', 'problems with orgasm', 'nose deformity',\n",
              "       'lump over jaw', 'sore in nose', 'hip weakness', 'back swelling',\n",
              "       'ankle stiffness or tightness', 'ankle weakness', 'neck weakness'],\n",
              "      dtype='object', length=378)"
            ]
          },
          "metadata": {},
          "execution_count": 16
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "https://colab.research.google.com/drive/1FvSWxWNek3U8IvoSphKEr7we3Pz_5u96#scrollTo=Y0j-7-nGqzmV&fullscreenOutput=true"
      ],
      "metadata": {
        "id": "tDOYWC7Mq_rx"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "df.nunique()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 458
        },
        "id": "XBRy7bA9rGlN",
        "outputId": "92712a10-a8a2-4a8d-f434-0d267fe96519"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "diseases                            773\n",
              "anxiety and nervousness               2\n",
              "depression                            2\n",
              "shortness of breath                   2\n",
              "depressive or psychotic symptoms      2\n",
              "                                   ... \n",
              "hip weakness                          1\n",
              "back swelling                         1\n",
              "ankle stiffness or tightness          1\n",
              "ankle weakness                        2\n",
              "neck weakness                         1\n",
              "Length: 378, dtype: int64"
            ],
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>0</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>diseases</th>\n",
              "      <td>773</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>anxiety and nervousness</th>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>depression</th>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>shortness of breath</th>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>depressive or psychotic symptoms</th>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>hip weakness</th>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>back swelling</th>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>ankle stiffness or tightness</th>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>ankle weakness</th>\n",
              "      <td>2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>neck weakness</th>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>378 rows × 1 columns</p>\n",
              "</div><br><label><b>dtype:</b> int64</label>"
            ]
          },
          "metadata": {},
          "execution_count": 17
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "df['diseases'].nunique()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ZJ4IYH9trXo_",
        "outputId": "3b5d9fc1-5eae-4b3c-aa3a-265b4a303b9b"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "773"
            ]
          },
          "metadata": {},
          "execution_count": 19
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "df['diseases'].unique()[:200]"
      ],
      "metadata": {
        "id": "6S9kQs75rPOp"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "df['hip weakness'].unique()"
      ],
      "metadata": {
        "id": "DNTGW3nQr7AM"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "df['hip weakness'][:6]"
      ],
      "metadata": {
        "id": "X6d2spjPsT28"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "df['ankle stiffness or tightness'][:5]"
      ],
      "metadata": {
        "id": "5inBgnZ3se3c"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "df['ankle weakness'].unique()"
      ],
      "metadata": {
        "id": "28LK_4-isnwi"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "5rjQ6uG8svLg"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "we need to drop values whose unique counbt is -0"
      ],
      "metadata": {
        "id": "KJbgAzdPsv_Y"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "g=df.nunique()"
      ],
      "metadata": {
        "id": "BKmlH934s58l"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "from sklearn.preprocessing import LabelEncoder\n",
        "from sklearn.model_selection import train_test_split\n",
        "import numpy as np\n",
        "import pandas as pd # Import pandas for Series operations\n",
        "\n",
        "# Drop columns with only one unique value (constant columns)\n",
        "# `g` contains the nunique values for each column, previously computed.\n",
        "constant_columns = g[g == 1].index.tolist()\n",
        "# Exclude 'diseases' from being dropped if it happens to be a constant column (unlikely here with 773 unique values)\n",
        "# and ensure it's not in the list of constant columns if it has 1 unique value due to data issue\n",
        "if 'diseases' in constant_columns:\n",
        "    constant_columns.remove('diseases')\n",
        "\n",
        "df_filtered = df.drop(columns=constant_columns, axis=1)\n",
        "print(f\"Dropped {len(constant_columns)} constant columns. New shape: {df_filtered.shape}\")\n",
        "\n",
        "# Separate features (X) and target (y)\n",
        "X = df_filtered.drop('diseases', axis=1)\n",
        "y = df_filtered['diseases']\n",
        "\n",
        "print(f\"Features (X) shape: {X.shape}\")\n",
        "print(f\"Target (y) shape: {y.shape}\")\n",
        "\n",
        "# Encode the target variable\n",
        "label_encoder = LabelEncoder()\n",
        "y_encoded = label_encoder.fit_transform(y)\n",
        "\n",
        "print(f\"Original target unique values: {y.nunique()}\")\n",
        "print(f\"Encoded target unique values: {np.unique(y_encoded).shape[0]}\")\n",
        "\n",
        "# Identify classes with only one member\n",
        "class_counts = pd.Series(y_encoded).value_counts()\n",
        "single_member_classes = class_counts[class_counts == 1].index\n",
        "\n",
        "# Filter out samples belonging to single-member classes\n",
        "# Get indices of samples NOT belonging to single-member classes\n",
        "indices_to_keep = np.isin(y_encoded, single_member_classes, invert=True)\n",
        "\n",
        "X_filtered = X.iloc[indices_to_keep]\n",
        "y_filtered = y_encoded[indices_to_keep]\n",
        "\n",
        "print(f\"\\nAfter filtering: Features (X_filtered) shape: {X_filtered.shape}\")\n",
        "print(f\"After filtering: Target (y_filtered) shape: {y_filtered.shape}\")\n",
        "print(f\"After filtering: Encoded target unique values: {np.unique(y_filtered).shape[0]}\")\n",
        "\n",
        "# Split the data into training and testing sets using the filtered data\n",
        "X_train, X_test, y_train, y_test = train_test_split(X_filtered, y_filtered, test_size=0.2, random_state=42, stratify=y_filtered)\n",
        "\n",
        "print(f\"\\nTraining and Testing Set Shapes:\")\n",
        "print(f\"X_train shape: {X_train.shape}\")\n",
        "print(f\"X_test shape: {X_test.shape}\")\n",
        "print(f\"y_train shape: {y_train.shape}\")\n",
        "print(f\"y_test shape: {y_test.shape}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "RQ-Av0eBtCim",
        "outputId": "0e2ee50d-28fb-4e69-a969-52bb1d912abf"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Dropped 49 constant columns. New shape: (246945, 329)\n",
            "Features (X) shape: (246945, 328)\n",
            "Target (y) shape: (246945,)\n",
            "Original target unique values: 773\n",
            "Encoded target unique values: 773\n",
            "\n",
            "After filtering: Features (X_filtered) shape: (246926, 328)\n",
            "After filtering: Target (y_filtered) shape: (246926,)\n",
            "After filtering: Encoded target unique values: 754\n",
            "\n",
            "Training and Testing Set Shapes:\n",
            "X_train shape: (197540, 328)\n",
            "X_test shape: (49386, 328)\n",
            "y_train shape: (197540,)\n",
            "y_test shape: (49386,)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ebe271a0"
      },
      "source": [
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import pandas as pd\n",
        "\n",
        "# Assuming y_filtered is available from previous steps (encoded and filtered target variable)\n",
        "# Get the counts of each disease class\n",
        "disease_counts = pd.Series(y_filtered).value_counts()\n",
        "\n",
        "# Get the top N most frequent diseases\n",
        "N = 20 # Number of top diseases to visualize\n",
        "top_n_diseases = disease_counts.head(N)\n",
        "\n",
        "# Decode the labels back to original disease names for better readability on the plot\n",
        "# This assumes `label_encoder` from previous steps is still available\n",
        "top_n_disease_names = label_encoder.inverse_transform(top_n_diseases.index)\n",
        "\n",
        "# Create a DataFrame for plotting\n",
        "plot_df = pd.DataFrame({'Disease': top_n_disease_names, 'Count': top_n_diseases.values})\n",
        "\n",
        "plt.figure(figsize=(12, 7))\n",
        "sns.barplot(x='Count', y='Disease', data=plot_df, palette='viridis')\n",
        "plt.title(f'Top {N} Disease Class Distributions')\n",
        "plt.xlabel('Number of Occurrences')\n",
        "plt.ylabel('Disease')\n",
        "plt.tight_layout()\n",
        "plt.show()"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "564d919f",
        "outputId": "fa65c4d9-2029-402d-9911-525dcafc5519"
      },
      "source": [
        "import mlflow\n",
        "import mlflow.sklearn\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix, ConfusionMatrixDisplay\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import itertools\n",
        "\n",
        "# Set MLflow tracking URI (if not already set, e.g., to a local directory or remote server)\n",
        "# mlflow.set_tracking_uri(\"http://127.0.0.1:5000\") # Uncomment and modify if using a remote MLflow server\n",
        "\n",
        "# Experiment name to organize runs\n",
        "mlflow.set_experiment(\"Disease_Classification_Models\")\n",
        "\n",
        "print(\"Starting MLflow run for Logistic Regression...\")\n",
        "with mlflow.start_run(run_name=\"Logistic_Regression_Baseline\"):\n",
        "    # Log parameters\n",
        "    params = {\n",
        "        \"solver\": \"saga\", # A good choice for large datasets and L1/L2 regularization\n",
        "        \"max_iter\": 1000, # Increased max_iter for convergence\n",
        "        \"random_state\": 42,\n",
        "        \"penalty\": \"l2\" # Default is l2, can also try 'l1' for feature selection\n",
        "    }\n",
        "    mlflow.log_params(params)\n",
        "\n",
        "    # Initialize and train the Logistic Regression model\n",
        "    model = LogisticRegression(**params)\n",
        "    print(\"Training Logistic Regression model...\")\n",
        "    model.fit(X_train, y_train)\n",
        "    print(\"Logistic Regression model trained.\")\n",
        "\n",
        "    # Make predictions\n",
        "    y_pred = model.predict(X_test)\n",
        "\n",
        "    # Evaluate the model\n",
        "    accuracy = accuracy_score(y_test, y_pred)\n",
        "    # precision, recall, f1-score support for multi-class\n",
        "    precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred, average='weighted', zero_division=0)\n",
        "\n",
        "    # Log metrics\n",
        "    mlflow.log_metric(\"accuracy\", accuracy)\n",
        "    mlflow.log_metric(\"precision\", precision)\n",
        "    mlflow.log_metric(\"recall\", recall)\n",
        "    mlflow.log_metric(\"f1_score\", f1_score)\n",
        "\n",
        "    print(f\"\\nModel Metrics:\")\n",
        "    print(f\"Accuracy: {accuracy:.4f}\")\n",
        "    print(f\"Precision (weighted): {precision:.4f}\")\n",
        "    print(f\"Recall (weighted): {recall:.4f}\")\n",
        "    print(f\"F1-Score (weighted): {f1_score:.4f}\")\n",
        "\n",
        "    # Log the model\n",
        "    mlflow.sklearn.log_model(model, \"logistic_regression_model\")\n",
        "\n",
        "    # Create and log Confusion Matrix visualization\n",
        "    cm = confusion_matrix(y_test, y_pred)\n",
        "    # Due to potentially large number of classes (754), a direct plot might be too dense.\n",
        "    # We'll plot a smaller sample or a summary, or simply save the matrix.\n",
        "    # For better visualization, we can show a heatmap of a subset or just a general overview.\n",
        "    plt.figure(figsize=(10, 8))\n",
        "    sns.heatmap(cm, annot=False, cmap='Blues', fmt='g') # Removed annot for readability with many classes\n",
        "    plt.title('Confusion Matrix for Logistic Regression (too many classes to display labels effectively)')\n",
        "    plt.xlabel('Predicted Label')\n",
        "    plt.ylabel('True Label')\n",
        "    plt.tight_layout()\n",
        "    cm_path = \"confusion_matrix_logistic_regression.png\"\n",
        "    plt.savefig(cm_path)\n",
        "    mlflow.log_artifact(cm_path)\n",
        "    plt.close() # Close the plot to free memory\n",
        "\n",
        "    # Log a simplified confusion matrix (e.g., top N classes, or overall performance)\n",
        "    # For now, just logging the image of the full matrix (without labels)\n",
        "\n",
        "    print(\"MLflow Run completed. Check the MLflow UI for details.\")\n"
      ],
      "execution_count": null,
      "outputs": [
        {
          "metadata": {
            "tags": null
          },
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "2026/08/19 15:45:35 INFO mlflow.store.db.utils: Creating initial MLflow database tables...\n",
            "2026/08/19 15:45:35 INFO mlflow.store.db.utils: Updating database tables\n",
            "2026/08/19 15:45:40 INFO mlflow.tracking.fluent: Experiment with name 'Disease_Classification_Models' does not exist. Creating a new experiment.\n"
          ]
        },
        {
          "metadata": {
            "tags": null
          },
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Starting MLflow run for Logistic Regression...\n",
            "Training Logistic Regression model...\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "003a0932"
      },
      "source": [
        "from sklearn.ensemble import RandomForestClassifier\n",
        "\n",
        "print(\"Starting MLflow run for Random Forest...\")\n",
        "with mlflow.start_run(run_name=\"Random_Forest_Classifier\"):\n",
        "    # Log parameters for Random Forest\n",
        "    params_rf = {\n",
        "        \"n_estimators\": 100, # Number of trees in the forest\n",
        "        \"max_depth\": None,   # Maximum depth of the tree (None means unlimited)\n",
        "        \"min_samples_split\": 2,\n",
        "        \"min_samples_leaf\": 1,\n",
        "        \"random_state\": 42,\n",
        "        \"n_jobs\": -1 # Use all available cores\n",
        "    }\n",
        "    mlflow.log_params(params_rf)\n",
        "\n",
        "    # Initialize and train the Random Forest model\n",
        "    rf_model = RandomForestClassifier(**params_rf)\n",
        "    print(\"Training Random Forest model...\")\n",
        "    rf_model.fit(X_train, y_train)\n",
        "    print(\"Random Forest model trained.\")\n",
        "\n",
        "    # Make predictions\n",
        "    y_pred_rf = rf_model.predict(X_test)\n",
        "\n",
        "    # Evaluate the model\n",
        "    accuracy_rf = accuracy_score(y_test, y_pred_rf)\n",
        "    precision_rf, recall_rf, f1_score_rf, _ = precision_recall_fscore_support(y_test, y_pred_rf, average='weighted', zero_division=0)\n",
        "\n",
        "    # Log metrics\n",
        "    mlflow.log_metric(\"accuracy\", accuracy_rf)\n",
        "    mlflow.log_metric(\"precision\", precision_rf)\n",
        "    mlflow.log_metric(\"recall\", recall_rf)\n",
        "    mlflow.log_metric(\"f1_score\", f1_score_rf)\n",
        "\n",
        "    print(f\"\\nRandom Forest Model Metrics:\")\n",
        "    print(f\"Accuracy: {accuracy_rf:.4f}\")\n",
        "    print(f\"Precision (weighted): {precision_rf:.4f}\")\n",
        "    print(f\"Recall (weighted): {recall_rf:.4f}\")\n",
        "    print(f\"F1-Score (weighted): {f1_score_rf:.4f}\")\n",
        "\n",
        "    # Log the model\n",
        "    mlflow.sklearn.log_model(rf_model, \"random_forest_model\")\n",
        "\n",
        "    # Create and log Confusion Matrix visualization for Random Forest\n",
        "    cm_rf = confusion_matrix(y_test, y_pred_rf)\n",
        "    plt.figure(figsize=(10, 8))\n",
        "    sns.heatmap(cm_rf, annot=False, cmap='Greens', fmt='g') # Using a different cmap for distinction\n",
        "    plt.title('Confusion Matrix for Random Forest (too many classes to display labels effectively)')\n",
        "    plt.xlabel('Predicted Label')\n",
        "    plt.ylabel('True Label')\n",
        "    plt.tight_layout()\n",
        "    cm_rf_path = \"confusion_matrix_random_forest.png\"\n",
        "    plt.savefig(cm_rf_path)\n",
        "    mlflow.log_artifact(cm_rf_path)\n",
        "    plt.close() # Close the plot to free memory\n",
        "\n",
        "    print(\"MLflow Run for Random Forest completed. Check the MLflow UI for details.\")"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "b1fde9f6"
      },
      "source": [
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "# Retrieve MLflow runs to compare model accuracies\n",
        "runs = mlflow.search_runs(experiment_names=[\"Disease_Classification_Models\"])\n",
        "\n",
        "# Filter for the runs of interest and extract accuracy\n",
        "lr_accuracy = runs[runs['tags.mlflow.runName'] == 'Logistic_Regression_Baseline']['metrics.accuracy'].iloc[0]\n",
        "rf_accuracy = runs[runs['tags.mlflow.runName'] == 'Random_Forest_Classifier']['metrics.accuracy'].iloc[0]\n",
        "\n",
        "# Create a DataFrame for plotting\n",
        "accuracy_data = pd.DataFrame({\n",
        "    'Model': ['Logistic Regression', 'Random Forest'],\n",
        "    'Accuracy': [lr_accuracy, rf_accuracy]\n",
        "})\n",
        "\n",
        "# Create the bar chart\n",
        "fig = plt.figure(figsize=(8, 6))\n",
        "sns.barplot(x='Model', y='Accuracy', data=accuracy_data, palette='viridis')\n",
        "plt.title('Model Accuracy Comparison')\n",
        "plt.ylabel('Accuracy')\n",
        "plt.ylim(0, 1) # Set y-axis limit from 0 to 1 for accuracy\n",
        "plt.grid(axis='y', linestyle='--', alpha=0.7)\n",
        "\n",
        "# Add accuracy values on top of the bars\n",
        "for index, row in accuracy_data.iterrows():\n",
        "    plt.text(index, row.Accuracy + 0.01, f'{row.Accuracy:.4f}', color='black', ha=\"center\")\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.show()\n"
      ],
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "4095c285"
      },
      "source": [
        "# Log the plot as an MLflow artifact\n",
        "with mlflow.start_run(run_name=\"Accuracy_Comparison_Plot\", nested=True) as run:\n",
        "    plot_path = \"model_accuracy_comparison.png\"\n",
        "    fig.savefig(plot_path)\n",
        "    mlflow.log_artifact(plot_path)\n",
        "    print(f\"Accuracy comparison plot logged as artifact in run {run.info.run_id}\")\n",
        "plt.close(fig) # Close the figure to free memory"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}